version: '3.8'

services:
  api-prod:
    build:
      context: .
      target: production
    container_name: HLS-api-prod
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${EXPOSE}:${PORT}"
      - "4000:4000"
    depends_on:
      - api_db
    networks:
      - some-network

  api_db:
    build:
      dockerfile: ./db/Dockerfile
    container_name: HLS-db-prod
    restart: unless-stopped
    command: postgres -c logging_collector=on
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_api:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql/postgresql.log
    networks:
      - some-network

volumes:
  postgres_api:
  postgres_logs:

networks:
  some-network:
    driver: bridge
