version: '3.8'

services:
  api-dev:
    build:
      context: .
      target: development
    container_name: HLS-api-dev
    command: npm run start:dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${EXPOSE}:${PORT}"
      - "5000:5000"
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - api_db
    networks:
      - some-network

  api_db:
    build:
      dockerfile: ./db/Dockerfile
    container_name: HLS-db-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_api:/data/db
    networks:
      - some-network

volumes:
  postgres_api:

networks:
  some-network:
    driver: bridge
