version: '3.8'

services:
  api-dev:
    build:
      context: .
      target: development
    container_name: api
    image: api-dev:latest
    command: npm run start:dev
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - api_db
    networks:
      - some-network

  api_db:
    build:
      dockerfile: ./db/Dockerfile
    container_name: postgres
    image: my-postgres
    restart: always
    command: postgres -c logging_collector=on
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: ${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglog:/var/log/postgresql
    networks:
      - some-network

networks:
  some-network:
    driver: bridge
